postgresdb:
  host: "localhost:5432"
  user: "paywise"
  password: "paywise"
  dbname: "paywisedb"
  sslmode: "disable"

testpostgresdb:
  host: "localhost:2345"
  user: "paywise"
  password: "paywise"
  dbname: "paywisedbtest"
  sslmode: "disable"