postgresdb:
  host: "localhost:5432"
  user: "paywise"
  fady: "fady"
  password: "paywise"
  dbname: "paywisedb"
  sslmode: "disable"

testpostgresdb:
  host: "localhost:2345"
  user: "paywise"
  password: "paywise"
  dbname: "paywisedbtest"
  sslmode: "disable"

paseto:
  symmetrickey: "fady123456789gamil123456789mahro"
  expiration: 15m