postgresdb:
  host: localhost:5432
  user: "paywise"
  password: "paywise"
  dbname: "paywisedb"
  sslmode: "disable"

testpostgresdb:
  host: "localhost:2345"
  user: "paywise"
  password: "paywise"
  dbname: "paywisedbtest"
  sslmode: "disable"

paseto:
  symmetrickey: "fady123456789gamil123456789mahro"
  access_token_expiration: 15m
  refresh_token_expiration: 24h


server:
  port: "0.0.0.0:8000"